### ISSUE TITLE
Make vfr.py work with Vapoursynth

### ISSUE THREAD

**Issue by wiiaboo** [wiiaboo/vfr#5]
Not using VS at the moment, so I have no idea where or how to start.

**Comment by dubhater** [comment]
To start: look for the first ``std.Trim``. One can also trim by slicing, but whatever.

http://www.vapoursynth.com/doc/functions/trim.html
http://www.vapoursynth.com/doc/pythonreference.html#slicing-and-other-syntactic-sugar

**Comment by wiiaboo** [comment]
Someone more interested than me has done it already: https://github.com/AzraelNewtype/audiocutter
