### ISSUE TITLE
Handle trims

### ISSUE THREAD

**Issue by Kamekameha** [wiiaboo/vfr#9]
Add some kind of support for trims in this format: Trim(clip, start, end).
In other words, support the presence of the 'clip' in the trim call.

Thanks in advance.

**Comment by wiiaboo** [comment]
Any name or specific name? As in, do you want to only pick trims that correspond to ClipX through an option?

**Comment by Kamekameha** [comment]
No, like it only reads the last two parameters, start and end frames. I've made scripts that I use trims calling a variable in the way specified above, but vfr.py can't handle three parameters when reading trims.

Obviously, this is mostly cosmetics in the workflow. The workaround is simply just copy-paste the trims and remove the 'clip' in the trim call before using this program.

**Comment by wiiaboo** [comment]
Haven't tested much, so let me know if it's working as intended.

**Comment by Kamekameha** [comment]
It works like a charm. Thanks a lot!

**Comment by Kamekameha** [comment]
Not related to this but the --IDR parameter is always giving K values instead of I when making qpfiles. Probably introduced in d8921b5b5961d9f2611731c52f642d27077f2b93.
